services:
  - type: web
    name: wavy-health-api
    env: go
    region: oregon
    branch: main
    goVersion: 1.25
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
